<a href="https://colab.research.google.com/github/LokeshVadlamudi/DeepLearningClass/blob/master/numpyLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
i = np.array([1,2])
j = np.array([2,3])
i + j

array([3, 5])

broadcasting is performing some action with scalar element on a multidimensional array

In [3]:
i + 2

array([3, 4])

In [4]:
p = np.ones((3,3))
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
k = np.array([1,2,3])

In [7]:
p + k

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

let us try mean feature

In [11]:
q = np.random.random((10,3))
q

array([[0.85271202, 0.44674505, 0.38777736],
       [0.73751917, 0.0954448 , 0.2474041 ],
       [0.60930523, 0.55535422, 0.37998519],
       [0.47795525, 0.2503168 , 0.72512036],
       [0.86701724, 0.27156533, 0.615014  ],
       [0.29931999, 0.11521293, 0.61948926],
       [0.45033014, 0.1400208 , 0.04052955],
       [0.58255934, 0.10097324, 0.92685342],
       [0.09807577, 0.53481035, 0.74701632],
       [0.64272146, 0.08382085, 0.99930308]])

In [14]:
qmean = q.mean(0)
qmean

array([0.56175156, 0.25942644, 0.56884926])