<a href="https://colab.research.google.com/github/LokeshVadlamudi/DeepLearningClass/blob/master/pyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
a = [1.0, 2.0, 1.0]

In [3]:

o = torch.ones(3)
o

tensor([1., 1., 1.])

In [5]:
o[1]

tensor(1.)

In [0]:
o[2] = 3.0

In [7]:
o

tensor([1., 1., 3.])

pass a list as a constructor

In [0]:
p = torch.tensor([2.0, 3.0, 4.0])


In [9]:
p

tensor([2., 3., 4.])

passing list of lists as a constructor

In [0]:
p = torch.tensor([[2.0, 3.0, 4.0],[2.0, 3.0, 4.0]])

In [11]:
p

tensor([[2., 3., 4.],
        [2., 3., 4.]])

print the shape

In [12]:
p.shape

torch.Size([2, 3])

we could also initilize tensor using size as constructor

In [0]:
p = torch.zeros(3, 2)

In [14]:
p

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

we can accesss all the elements in a tensor using .storage property

In [19]:
p = torch.tensor([[1.0, 4.0], [3.0, 5.0]])
p.storage()

 1.0
 4.0
 3.0
 5.0
[torch.FloatStorage of size 4]

stride is a tuple indicating the number of elements in the storage that have to be
skipped when the index is increased by 1 in each dimension.

In [20]:
p.stride()

(2, 1)

 transposing now

In [0]:
p_t = p.t()

In [22]:
p_t

tensor([[1., 3.],
        [4., 5.]])

we can easily verify that the two tensors share storage

In [23]:
id(p.storage()) == id(p_t.storage())

True

 To allocate a tensor of the right numeric type, you can specify the proper dtype as
an argument to the constructor

In [0]:
d_p = torch.ones(10, 2, dtype=torch.double)

In [26]:
d_p.dtype

torch.float64

To get a NumPy array out of your points tensor

In [7]:
p = torch.ones(3, 4)
p_np = p.numpy()
p_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

Serializing tensors

In [0]:
# torch.save(p, '/content/ourpoints.t')

In [0]:
# p = torch.load('/content/ourpoints.t')

Moving tensors to the GPU

In [0]:
p_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]],device='cuda')

In [4]:
p_gpu

tensor([[1., 4.],
        [2., 1.],
        [3., 4.]], device='cuda:0')

You could instead copy a tensor created on the CPU to the GPU

In [0]:
p_gpu = p.to(device='cuda')

multiplication

In [0]:
# points = 2 * points
# points_gpu = 2 * points.to(device='cuda') 

Image

In [0]:
import imageio

In [0]:
# img_arr = imageio.imread('/content/loki.jpg')
# img_arr.shape

In [0]:
# img = torch.from_numpy(img_arr)
# out = torch.transpose(img, 0, 2)

Volumetric data

In [0]:
import imageio
# dir_path = "/content/2-LUNG"
# vol_arr = imageio.volread(dir_path, 'DICOM')
# vol_arr.shape

the layout is different from what PyTorch expects, due to the lack of
channel information. You’ll have to make room for the channel dimension by using
unsqueeze:

In [0]:
# vol = torch.from_numpy(vol_arr).float()
# vol = torch.transpose(vol, 0, 2)
# vol = torch.unsqueeze(vol, 0)
# vol.shape